### ISSUE TITLE
BUG - FORMULA SQL IS LOWERCASeD

### ISSUE THREAD

**Issue by dfagnan** [fivetran/dbt_salesforce_formula_utils#34]
**Are you a current Fivetran customer?** 
Yes

David , Artica

**Describe the bug**
The formula SQL is lower cased so for example:
`CASE WHEN field = 'Bob' THEN 1 ELSE 0 END as isBob`

would become
`case when field = 'bob' then 1 else 0 end as isbob`

And therefore fail to match `Bob` correctly.

**Steps to reproduce**
Try a case statement Salesforce formula that is case-sensitive

See line causing this here: https://github.com/fivetran/dbt_salesforce_formula_utils/blob/main/macros/sfdc_get_formula_column_values.sql#L26

**Expected behavior**
I would expect it not to change CASE statements inside sql formulas.

**Package Version**

```yml
copy packages.yml here
```

**Warehouse**

 
- [ ] BigQuery
- [ ] Redshift
- [ X] Snowflake
- [ ] Postgres
- [ ] Databricks
- [ ] Other (provide details below)

**Are you interested in contributing to this package?** 

- [ ] Yes, I can do this and open a PR for your review.
- [X ] Possibly, but I'm not quite sure how to do this. I'd be happy to do a live coding session with someone to get this fixed. 
- [ ] No, I'd prefer if someone else fixed this.  I don't have the time and/or don't know what the root cause of the problem is.

**Comment by dfagnan** [comment]
Unrelated - is there a Fivetran opinion on how to use this with your other packages? https://github.com/fivetran/dbt_salesforce_source
They seem somewhat incompatible / conflicting in that the other packages don't know about "fivetran_formula"

**Comment by fivetran-joemarkiewicz** [comment]
Hey @dfagnan, thanks so much for creating this issue!

I actually just encountered a similar issue where a `convert_timezone` function was not working because I lower case the fields and the timezone is not able to find a match. I believe the snippet of code you pointed out is right on track with where I am thinking we should make some adjustments to ensure we do not change the casing.

Since you helped point this out, it would be great if you wanted to open a PR for this quick fix. If you wanted to make the small adjustment you highlighted and open the PR on this branch, then I can help debug and test this further to ensure there are no other changes need. Let me know if you have any question.

> Unrelated - is there a Fivetran opinion on how to use this with your other packages? https://github.com/fivetran/dbt_salesforce_source
They seem somewhat incompatible / conflicting in that the other packages don't know about "fivetran_formula"

^ That is a great question! While the two seem unrelated, you actually can use the two package together. The salesforce_source package by default looks at the raw tables synced by Fivetran to generate the staging and then final models. However, if you wanted the source package to look at the output of the models generated via this macro you could simply override the variables in your dbt_project.yml to point to the new models generated from this macro. An example of the override would look like the below config:

```yml
vars:
  salesforce_source:
    account: "{{ ref('account_formula_view') }}" 
    opportunity: "{{ ref('opportunity_formula_view') }}" 
    user: "{{ ref('user_formula_view') }}" 
    user_role: "{{ ref('user_role_formula_view') }}" 
```
The salesforce_source package would then reference these models when running the downstream package models. 

You make a great point though that this is not entirely clear. I will make a note for myself and the team to put together some supporting docs to show how this may be possible. Thanks for the helpful question! 😄

**Comment by fivetran-joemarkiewicz** [comment]
Hi @dfagnan this issue should be resolved in the latest release of the dbt package! Let me know if you continue experiencing the casing issue.

Thanks!

**Comment by dfagnan** [comment]
Thanks @fivetran-joemarkiewicz - I don't think I had any issues related to this after updating. I regret I wasn't more helpful on this one but appreciate your support.
