### ISSUE TITLE
BUG - Salesforce system variables left in formula SQL

### ISSUE THREAD

**Issue by djbelknapdbs** [fivetran/dbt_salesforce_formula_utils#5]
**Are you a current Fivetran customer?** 
Yes

**Describe the bug**
There are fields with dots in the SQL formulas that break, at least in Snowflake. This bug report is where the formula references a Salesforce variable like `$User.ProfileId`

**Steps to reproduce**
1. Create a formula in Salesforce that references a Salesforce variable like $User
2. Sync that object with Fivetran
3. Check the SQL field in the formulas table for that object and see that it includes $User.Something
4. Run this package on that object
5. Get an error about an unexpected `.`

**Expected behavior**
Not sure if there's a good way to get the Salesforce variables in - if so, that's likely a relationship. Either way, the SQL field should probably get NULLed out since it's either a relationship or some other value this package doesn't know about.

**Project variables configuration**

```yml
copy dbt_project.yml here
```

**Package Version**

```yml
  - package: fivetran/salesforce_formula_utils
    version: [">=0.1.0", "<0.2.0"]
```
(I'm working from a fork doing some troubleshooting, but I'm even with main.)

**Warehouse**

 
- [ ] BigQuery
- [ ] Redshift
- [x] Snowflake
- [ ] Postgres
- [ ] Databricks
- [ ] Other (provide details below)

**Please indicate the level of urgency** 
Medium - it's preventing us from switching our production sync from another tool to Fivetran, but it's not affecting something currently in production.

**Are you interested in contributing to this package?** 

- [ ] Yes, I can do this and open a PR for your review.
- [x] Possibly, but I'm not quite sure how to do this. I'd be happy to do a live coding session with someone to get this fixed. 
- [ ] No, I'd prefer if someone else fixed this.  I don't have the time and/or don't know what the root cause of the problem is.

I'm working on a fork and if it's something to handle in dbt I can contribute. This might be an issue upstream in the Fivetran connector though.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @djbelknapdbs thanks opening this Issue and for your detailed description!

I believe this would be a fix that is best implemented at the connector level so we can reference the variable. As the dbt package would fail regardless of the `.` since it wouldn't know what the variable is (to the best of my knowledge). I will bring this to the attention of our internal product team to see what next steps would be for implementing a solution.

I will post back here with more details in the future.

**Comment by fivetran-joemarkiewicz** [comment]
@djbelknapdbs I have been able to contact our internal team and believe the best move forward is to create a support ticket through our [Fivetran Support](https://support.fivetran.com/hc/en-us) portal since this is not an issue that can be directly solved with this dbt package. Creating this support ticket will allow our team to understand the observed behavior in more detail and help resolve the issue.

Let me know if you have any questions when creating the ticket. Thanks!

**Comment by fivetran-joemarkiewicz** [comment]
Per above comment I will close this Issue. Please feel free to reach out if you have any other questions following the creation of the support ticket.

Thanks!
