### ISSUE TITLE
BUG - References to fields that don't exist on an object

### ISSUE THREAD

**Issue by djbelknapdbs** [fivetran/dbt_salesforce_formula_utils#8]
**Are you a current Fivetran customer?** 
Yes

**Describe the bug**
A formula references a field that isn't synced so the formula breaks. In this case, both fields are on the contact but the issue happens on the account object.

**Steps to reproduce**
1. In Salesforce, make two Contact fields
  a. A regular field
  b. A second field that references the regular field in a formula
2. Sync the data in Fivetran - in our case, `field a` doesn't show up in the field list to sync. (Or to force the issue, uncheck the regular field so it doesn't sync)
3. Check the formulas table to see that `field b` has SQL that references `field a`
4. Run this package - get an error that `field a` doesn't exist

**Expected behavior**
The package should check that fields referenced in a formula exist either on the object or as another formula. 

**Package Version**

```yml
  - package: fivetran/salesforce_formula_utils
    version: [">=0.1.0", "<0.2.0"]
```

**Warehouse**

 
- [ ] BigQuery
- [ ] Redshift
- [x] Snowflake
- [ ] Postgres
- [ ] Databricks
- [ ] Other (provide details below)

**Please indicate the level of urgency** 
Medium - a few issues are keeping us from switching to Fivetran for production replication.

**Are you interested in contributing to this package?** 

- [ ] Yes, I can do this and open a PR for your review.
- [x] Possibly, but I'm not quite sure how to do this. I'd be happy to do a live coding session with someone to get this fixed. 
- [ ] No, I'd prefer if someone else fixed this.  I don't have the time and/or don't know what the root cause of the problem is.

I'm looking into validating formula references, but it'll be complicated to pick column names out of the formulas. Any suggestions on parsing formulas for column names?

**Comment by fivetran-joemarkiewicz** [comment]
HI @djbelknapdbs thank you for opening this issue and your detailed descriptions!

From the information you provided there seem to be two key problems:
1. Salesforce fields are not being synced 
2. Formula fields which then reference these fields which didn't sync fail because the field doesn't exist.

I will coordinate with our internal team to help resolve the first issue. I can also include logic for the second issue which would have the macro ignore formulas that reference empty fields. This would result in the formula field not being included in the final table. Because it is best that the field is synced and the formula field references that field, I will prioritize trying to work with our internal teams to resolve that first issue.

In the meantime, I will add the request to skip fields that reference non-synced formulas to our next sprint. I will continue to post here for updates on this issue. Let me know if you have any questions. Thanks!

**Comment by fivetran-joemarkiewicz** [comment]
@djbelknapdbs I have been able to contact our internal team and believe the best move forward is to create a support ticket through our [Fivetran Support](https://support.fivetran.com/hc/en-us) portal since this is not an issue that can be directly solved with this dbt package. Creating this support ticket will allow our team to understand the observed behavior in more detail and help resolve the issue.

Let me know if you have any questions when creating the ticket. Thanks!

**Comment by fivetran-joemarkiewicz** [comment]
Per above comment I will close this Issue. Please feel free to reach out if you have any other questions following the creation of the support ticket.

Thanks!
